### ISSUE TITLE
[BUG REPORT] return statement outside function definition

### ISSUE THREAD

**Issue by lucasace** [cimplec/sim-c#257]
**Describe the bug**
Simc allows for return function to be outside function definition scope

**To Reproduce**
simc code:
```bash
fun a(){

	print("hello world")
}
return 1
MAIN
	a()
END_MAIN
```
c code generated:
```bash
 #include <stdio.h>

int a(void) {
	printf("hello world");
}

	return 1;

int main() {
	a();

	return 0;
}
```
**Expected behavior**
 should give error stating return function used outside function definition

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux

**Comment by YJDoc2** [comment]
I would like to work on this

**Comment by frankhart2018** [comment]
Sure @YJDoc2. Assigning this to you. Thanks for showing interest to contribute.

**Comment by YJDoc2** [comment]
Is one allowed to give custom return statement in main function or not?

**Comment by frankhart2018** [comment]
It is not part of the current version, you are welcome to add that.

**Comment by YJDoc2** [comment]
Hey I have added the checks and support for return statement, but when I was running tests, I am getting ImportError :
`ImportError: bad magic number in 'op_code': b'\x03\xf3\r\n'` . I had some issued while running the code as well and had to make changes in the import syntax to make it run. This would probably be due to my setup, but other than that I have run the updated code for checking and validation return statement, and it works as expected. Is it ok if I make a PR anyway without running test (Only with the changes for return statement), and if possible you can run test before merge?

**Comment by frankhart2018** [comment]
Merged, thanks for your contribution @YJDoc2.
